---
title: "Zabalo Report"
author: "Morgan Manning"
date: "8/15/2023"
output: html_document
---

- Prepare MarkDown report
    - two page tops
    - short intro paragraph
    - How we did it (equation for negative exponential)
    - summary table for best models
    - AIC table

```{r set up, echo=FALSE}
require(unmarked)
require(dplyr)
require(ggplot2)


```



```{r clumping, include=FALSE}
# occupancy data
peccary = read.csv("CollaredPeccary.csv")
peccary = data.frame(peccary[,-1], row.names=peccary[,1]) #rownames = stations

deer = read.csv("Deer.csv")
deer = data.frame(deer[,-1], row.names=deer[,1]) #rownames = stations

paca = read.csv("Paca.csv")
paca = data.frame(paca[,-1], row.names=paca[,1]) #rownames = stations

# occupancy covariates
load('R Objects/siteCovs2018.RData')
names(siteCovariate)

# stations info
stations <- read.csv("Stations2018.csv")
hunting <- read.csv("HuntingData2018.csv")
cameraRecords <- read.csv("RecordTable2018.csv")


############################################################################
########################### PICK A SPECIES #################################
####################### & FORMAT FOR UNMARKED ##############################
############################################################################

species <- peccary # pick which species to proceed with


# data as matrix
y <- as.matrix(species)
y <- (y[ order(as.numeric(row.names(y))), ]) #order matters


#################### IF YOU WANT TO POOL THE COLUMNS ###########################
# paste columns together, then if there's a 1 -> 1, if there's no 1 but a 0 -> 0, if only NAs -> NA
y <- as.matrix(species)
y <- (y[ order(as.numeric(row.names(y))), ]) #order matters

#### ***** CHANGE COMBINATION FACTOR HERE ***** ####
clumpEvery <- 10 
nClumpedColumns <- ncol(y)/clumpEvery
clumpedMatrix <- matrix(0, ncol = nClumpedColumns, nrow = 30) # bc there are 30 stations

clumpStart <- seq(1, ncol(y), by = clumpEvery) # the first column in the clump
clumpEnd <- seq(clumpEvery, ncol(y), by = clumpEvery) # the last column in the clump

### make the clumped matrix
for (k in 1:30){
  for (j in 1:ncol(clumpedMatrix)){
    if(all(is.na(y[k, clumpStart[j]:clumpEnd[j]])) == TRUE) {
      clumpedMatrix[k,j] <- NA
    } else if (sum(y[k, clumpStart[j]:clumpEnd[j]], na.rm=TRUE) >= 1) {
      clumpedMatrix[k,j] <- 1
    } else {
      clumpedMatrix[k,j] <- 0
    }
  }
} # the clumped matrix is made
############################################################################

# unmarked df for single species
ufo <- unmarkedFrameOccu(clumpedMatrix, # 'y' or 'combinedTime'
                        siteCovs = siteCovariate,
                        obsCovs = NULL)

uncombinedUFO <- unmarkedFrameOccu(y, # 'y' or 'combinedTime'
                                   siteCovs = siteCovariate,
                                   obsCovs = NULL)

plot(ufo)
require(reshape2)
colnames(ufo@y) <- 1:ncol(ufo@y)
meltedComb <- melt(ufo@y)
meltedComb$value <- as.factor(meltedComb$value)
ggplot(meltedComb, aes(Var2, Var1, fill = value)) + 
  geom_tile(colour = "gray50") +
  scale_fill_manual(values=c("gray75", "red3"), na.value="white", name = "") +
  scale_x_continuous(breaks = seq(0, ncol(ufo@y), by = 2)) +
  scale_alpha_identity(guide = "none") +
  coord_equal(expand = 0) +
  xlab("Time (1 unit = 8 days)") +
  ylab("Camera trap site") +
  theme_bw()

plot(uncombinedUFO)
# require(reshape2)
colnames(uncombinedUFO@y) <- 1:ncol(uncombinedUFO@y)
meltedUncomb <- melt(uncombinedUFO@y)
meltedUncomb$value <- as.factor(meltedUncomb$value)
ggplot(meltedUncomb, aes(Var2, Var1, fill = value)) + 
  geom_tile(colour = "gray50") +
  scale_fill_manual(values=c("gray75", "red3"), na.value="white", name = "") +
  scale_x_continuous(breaks = seq(0, ncol(uncombinedUFO@y), by = 4)) +
  scale_alpha_identity(guide = "none") +
  coord_equal(expand = 0) +
  xlab("Time (1 unit = 2 days)") +
  ylab("Camera trap site") +
  theme_bw()
```










```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pressure, echo=FALSE}
plot(pressure)
```
